class Exception1
{
	public static void main(String arg[])
	{
	  System.out.println("inside main");

	  int arr[] = {10,20,30,40,50};

	  System.out.println("Array created");
	  System.out.println("Array element at index 5 is:"+arr[5]);//exception
	  System.out.println("End of main");

	}
}